resilience4j:
  retry:
    instances:
      basic:
        maxRetryAttemps: 2
        waitDuration: 3s

      fallback:
        maxRetryAttempts: 3
        waitDuration: 2s

      intervalFunctionExponential:
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        maxRetryAttempts: 6
        waitDuration: 1s

      intervalFunctionRandom:
        enableRandomizedWait: true
        maxRetryAttempts: 3
        randomizedWaitFactor: 0.5
        waitDuration: 2s


  ratelimiter:
    instances:

      basic:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 1s

      timeout:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 250ms


      multipleRateLimiters_rps_limiter:
        limitForPeriod: 2
        limitRefreshPeriod: 1s
        timeoutDuration: 2s

      multipleRateLimiters_rpm_limiter:
        limitForPeriod: 40
        limitRefreshPeriod: 1m
        timeoutDuration: 2s


